# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PingPongService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15PingPongService.proto\x12\x11\x63om.protocol.grpc\"4\n\x0eSayPingRequest\x12\x10\n\x08gameName\x18\x03 \x01(\t\x12\x10\n\x08pingWord\x18\x01 \x01(\t\"<\n\x0fSayPongResponse\x12\x10\n\x08pongWord\x18\x02 \x01(\t\x12\x17\n\x0fgameDescription\x18\x04 \x01(\t2_\n\x0fPingPongService\x12L\n\x03say\x12!.com.protocol.grpc.SayPingRequest\x1a\".com.protocol.grpc.SayPongResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PingPongService_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SAYPINGREQUEST']._serialized_start=44
  _globals['_SAYPINGREQUEST']._serialized_end=96
  _globals['_SAYPONGRESPONSE']._serialized_start=98
  _globals['_SAYPONGRESPONSE']._serialized_end=158
  _globals['_PINGPONGSERVICE']._serialized_start=160
  _globals['_PINGPONGSERVICE']._serialized_end=255
# @@protoc_insertion_point(module_scope)
